language: node_js

node_js:
  - 'node'
dist: xenial
sudo: required
services:
  - xvfb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

install:
  - travis_wait 30 npm install
  - npm install codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  code_climate:
    repo_token: f45df226a75d3a1995f101fe89920334b4114ce4f2aa1256dcbb3a36884b6040
